version: "3.8"

services:
  test_db:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=testdb

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - ENV=test
      - DATABASE_URL=postgresql://root:root@test_db:5432/testdb
    depends_on:
      - test_db
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
    volumes:
      - .:/app
    working_dir: /app

networks:
  testnet:
    driver: bridge
